language: java
sudo: false

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar "https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.3/codacy-coverage-reporter-4.0.3-assembly.jar"

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r starter/target/site/jacoco/jacoco.xml
