language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  
matrix:
  allow_failures:
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11
  
sudo: false

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly.jar "https://github.com/codacy/codacy-coverage-reporter/releases/download/6.0.0/codacy-coverage-reporter-6.0.0-assembly.jar"

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly.jar report -l Java -r starter/target/site/jacoco/jacoco.xml
