ssh:
  shell:
    actuator:
      excludes:
      - audit
    prompt:
      color: cyan
      text: 'sample-app::>'
    password: pass

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    threaddump:
      enabled: false