ssh:
  shell:
    actuator:
      excludes:
      - audit
    prompt:
      color: cyan
      text: 'sample-app::>'
    password: pass

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    threaddump:
      enabled: false

logging:
  level:
    com.github.fonimus: debug

info:
  build:
    groupId: ${project.artifactId}
    artifactId: ${project.groupId}
    version: ${project.version}
  dependencies:
    spring-boot: ${spring-boot.version}
    spring-shell: ${spring-shell.version}
