name: Build Dependabot

on:
  pull_request_target

jobs:
  build:
    name: Build
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: fonimus/ssh-shell-spring-boot/.github/workflows/reusable-build.yml@main
    with:
      sonar_analysis: false
